baseURL = "https://naughty-roentgen-b02db4.netlify.app"
languageCode = "en-us"
summaryLength = "10"
theme = "kross-hugo"
title = "Pavi"
[[menu.main]]
URL = "about"
name = "About"
weight = 1
[[menu.main]]
URL = "blog"
name = "Blog"
weight = 2
[[menu.main]]
URL = "portfolio"
name = "Portfolio"
weight = 3
[[menu.main]]
URL = "talks"
name = "Talks"
weight = "4"
[params]
address = "Toronto, Ontario"
author = "Pavitra Logeswaran"
copyright = "Copyright &copy; Pavitra Logeswaran 2020"
description = "Pavitra Logeswaran is a Toronto-based multidisciplinary designer specializing in user experience and visual design."
email = "pavilogeswa@gmail.com"
home = "Home"
theme_color = "#41228e"
[params.contact]
enable = false
form_action = "#"
[params.cookies]
enable = false
expire_days = 2
[params.map]
enable = false
gmap_api = "https://maps.googleapis.com/maps/api/js?key=&#038;types=(cities)&#038;libraries=places&#038;language=en"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[params.preloader]
enable = false
preloader = "images/preloader.gif"
[[params.social]]
URL = "https://www.instagram.com/pavi.design"
icon = "ti-inst"
[[params.social]]
URL = "https://dribbble.com/Pavitra"
icon = "ti-drib"
[[params.social]]
URL = "https://twitter.com/pavi_design"
icon = "ti-twi"
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true